name: Tests
on: [push]

jobs:
  lint-test:
    name: Lint + Test
    uses: gsa/data.gov/.github/workflows/ckan-test.yml@ckan-reusable-workflow
    with:
      ext_name: usmetadata
      plugins: usmetadata
    secrets: inherit
